### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by xcomcadx** [speedyHKjournalist/OpenMapleClient#2]
can you provide some instructions on how to use this, or at least get it running.
When running gradlew.bat i get BUILD FAILED

**Comment by speedyHKjournalist** [comment]
I'm building on MacBook M1 Pro, let me test on x86 machine when I'm free.

**Comment by speedyHKjournalist** [comment]
My friend built successfully with Android Studio on Windows, what issue did you met ?
