### ISSUE TITLE
where can i get the nx files?

### ISSUE THREAD

**Issue by danzoo** [speedyHKjournalist/OpenMapleClient#3]

**Comment by speedyHKjournalist** [comment]
https://mega.nz/file/Z8FnHQjB#j_0_Hg_GqB2-MbK6OsQd4zlVq0nmgd9OYKrE1U4_PcA
https://mega.nz/file/BhNwWRSZ#mSSV6452km6X5UHQqKdzmldqXY2UAbzVsExPHh7c9c4

I'm still working on NPC talk issues and build machine is Macbook M1, currently there are many bugs.

**Comment by speedyHKjournalist** [comment]
Done.
